apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kconnect-console.fullname" . }}
  labels:
    {{- include "kconnect-console.labels" . | nindent 4 }}
data:
  KAFKA_CONNECT_URL: {{ required "kafkaConnect.url is required!" .Values.kafkaConnect.url | quote }}
