apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kconnect-console.fullname" . }}-proxy
  labels:
    {{- include "kconnect-console.proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.proxy.autoscaling.enabled }}
  replicas: {{ .Values.proxy.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kconnect-console.proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kconnect-console.proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kconnect-console.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: proxy
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.proxy.service.targetPort }}
          protocol: TCP
        env:
        - name: KAFKA_CONNECT_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "kconnect-console.fullname" . }}
              key: KAFKA_CONNECT_URL
        livenessProbe:
          {{- toYaml .Values.proxy.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.proxy.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.proxy.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
