apiVersion: v1
kind: Service
metadata:
  name: {{ include "kconnect-console.fullname" . }}-proxy
  labels:
    {{- include "kconnect-console.proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kconnect-console.proxy.selectorLabels" . | nindent 4 }}
