apiVersion: v1
kind: Service
metadata:
  name: {{ include "kconnect-console.fullname" . }}-web
  labels:
    {{- include "kconnect-console.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kconnect-console.web.selectorLabels" . | nindent 4 }}
