name: Feature request
description: Suggest an enhancement for kconnect-console.
labels:
  - type:feature
body:
  - type: markdown
    attributes:
      value: |
        Share the improvement you would like to see. Automation will use these details to stage a work package branch.
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which area should be updated?
      options:
        - web
        - proxy
        - docker
        - unknown
      default: web
    validations:
      required: true
  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: Estimated size of the change.
      options:
        - S
        - M
        - L
      default: M
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: What should change?
      description: Provide context, acceptance criteria, or user stories.
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: Likely files or directories
      description: Optional hints such as file paths or globs.
      placeholder: proxy/pkg/**/*.go
    validations:
      required: false
