name: Auto merge

on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Attempt merge when checks are green
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.setFailed('No pull request payload.');
              return;
            }
            if (pr.draft) {
              core.info('Pull request is still a draft. Skipping auto-merge.');
              return;
            }
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const headSha = pr.head.sha;
            const combined = await github.rest.repos.getCombinedStatusForRef({
              owner,
              repo,
              ref: headSha
            });
            if (combined.data.state !== 'success') {
              core.info(`Combined status is ${combined.data.state}. Waiting for success.`);
              return;
            }
            const checks = await github.rest.checks.listForRef({
              owner,
              repo,
              ref: headSha
            });
            const failing = checks.data.check_runs.filter((run) => ['failure', 'timed_out', 'cancelled', 'action_required'].includes(run.conclusion));
            if (failing.length > 0) {
              core.info('At least one check run failed.');
              return;
            }
            const pending = checks.data.check_runs.filter((run) => run.status !== 'completed');
            if (pending.length > 0) {
              core.info('Some checks are still in progress.');
              return;
            }
            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: pr.number,
              merge_method: 'squash'
            });
            core.info(`Pull request #${pr.number} merged automatically.`);
