name: Publish Helm Chart

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Use the release tag when triggered by release, otherwise use default SHA
          ref: ${{ github.event.release.tag_name || github.sha }}

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Package Helm Chart
        run: |
          cd helm
          helm package kconnect-console
          helm repo index . --url https://mcnabb998.github.io/kconnect-console

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'helm'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
