name: AI scheduler

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ai/state
        uses: actions/checkout@v4
        with:
          ref: ai/state
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install minimatch@9

      - name: Run scheduler script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node .github/scripts/scheduler.mjs

      - name: Commit queue and locks update
        run: |
          if git status --short | grep -E '\.ai/(queue|locks)\.json'; then
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git commit -am 'chore: update AI scheduler state'
            git push origin HEAD:ai/state
          else
            echo 'No scheduler changes to commit.'
          fi
